import { useState } from 'react'
import {
  View, Text, TextInput, ScrollView, StyleSheet,
  TouchableOpacity, Alert, Switch,
} from 'react-native'
import { SafeAreaView } from 'react-native-safe-area-context'
import { useRouter } from 'expo-router'
import { useAppStore } from '../../src/store'
import { Colors, Typography, Spacing, Radius, Shadows, CAREER_FIELDS, JOB_TYPES, SKILL_SUGGESTIONS } from '../../src/constants'
import { LogoMark } from '../../src/components/brand'

function Chip({ label, selected, onPress }: { label: string; selected: boolean; onPress: () => void }) {
  return (
    <TouchableOpacity onPress={onPress} activeOpacity={0.7}
      style={[styles.chip, selected && styles.chipSelected]}>
      <Text style={[styles.chipText, selected && styles.chipTextSelected]}>
        {selected ? '✓ ' : ''}{label}
      </Text>
    </TouchableOpacity>
  )
}

export default function ProfileScreen() {
  const router = useRouter()
  const { profile, updateProfile, setOnboardingComplete, resetCheckin } = useAppStore()

  const [name, setName]       = useState(profile?.name ?? '')
  const [email, setEmail]     = useState(profile?.email ?? '')
  const [school, setSchool]   = useState(profile?.school ?? '')
  const [major, setMajor]     = useState(profile?.major ?? '')
  const [location, setLocation] = useState(profile?.location ?? '')
  const [fields, setFields]   = useState<string[]>(profile?.fields ?? [])
  const [types, setTypes]     = useState<string[]>(profile?.jobTypes ?? [])
  const [skills, setSkills]   = useState<string[]>(profile?.skills ?? [])
  const [customSkill, setCustomSkill] = useState('')
  const [wantsSchols, setWantsSchols] = useState(profile?.wantsScholarships ?? true)
  const [saved, setSaved]     = useState(false)
  const [activeSection, setActiveSection] = useState<string>('basics')

  const toggle = (arr: string[], set: (a: string[]) => void, val: string) =>
    set(arr.includes(val) ? arr.filter(x => x !== val) : [...arr, val])

  const addCustomSkill = () => {
    const s = customSkill.trim()
    if (!s || skills.includes(s)) return
    setSkills(prev => [...prev, s])
    setCustomSkill('')
  }

  const saveChanges = () => {
    if (!name.trim()) { Alert.alert('', 'Name is required!'); return }
    updateProfile({ name: name.trim(), email: email.trim(), school, major, location, fields, jobTypes: types, skills, wantsScholarships: wantsSchols })
    setSaved(true)
    setTimeout(() => setSaved(false), 2000)
    Alert.alert('Saved!', 'Your profile has been updated.')
  }

  const generateResumeText = () => {
    const lines = [
      name.toUpperCase(),
      email,
      school ? `${school}${major ? ' | ' + major : ''}` : major,
      '',
      '─── SKILLS ───────────────────────────────────────',
      skills.join(' · '),
      '',
      '─── CAREER INTERESTS ────────────────────────────',
      fields.join(', '),
      '',
      '─── JOB PREFERENCES ─────────────────────────────',
      types.join(', '),
      location ? `Location preference: ${location}` : '',
      '',
      '─── GENERATED BY CAREER BUDDY ───────────────────',
      'careerbud.app',
    ].filter(Boolean)
    return lines.join('\n')
  }

  const [resumeCopied, setResumeCopied] = useState(false)

  const handleGenerateResume = async () => {
    if (skills.length === 0) {
      Alert.alert('Add skills first', 'Add at least a few skills before generating a resume draft.')
      return
    }
    const text = generateResumeText()
    try {
      if (typeof navigator !== 'undefined' && navigator.clipboard) {
        await navigator.clipboard.writeText(text)
      }
      setResumeCopied(true)
      setTimeout(() => setResumeCopied(false), 3000)
    } catch (err) {
      console.log('clipboard error', err)
      // fallback: just show copied state anyway since text is displayed in preview
      setResumeCopied(true)
      setTimeout(() => setResumeCopied(false), 3000)
    }
  }

  const SECTIONS = ['basics', 'interests', 'skills', 'resume']

  return (
    <SafeAreaView style={styles.safe}>
      {/* Custom header with logo */}
      <View style={styles.header}>
        <View style={styles.headerLeft}>
          <LogoMark size={32} />
          <Text style={styles.headerTitle}>Settings</Text>
        </View>
        <TouchableOpacity onPress={() => router.back()} style={styles.closeBtn}>
          <Text style={styles.closeBtnText}>✕</Text>
        </TouchableOpacity>
      </View>

      {/* Avatar row */}
      <View style={styles.avatarSection}>
        <View style={styles.avatar}>
          <Text style={styles.avatarText}>{name?.[0]?.toUpperCase() ?? '?'}</Text>
        </View>
        <View>
          <Text style={styles.avatarName}>{name || 'Your name'}</Text>
          <Text style={styles.avatarSchool}>{school || 'Add your school'}</Text>
        </View>
      </View>

      {/* Section tabs */}
      <View style={styles.sectionTabs}>
        {SECTIONS.map(s => (
          <TouchableOpacity
            key={s}
            style={[styles.sectionTab, activeSection === s && styles.sectionTabActive]}
            onPress={() => setActiveSection(s)}
          >
            <Text style={[styles.sectionTabText, activeSection === s && styles.sectionTabTextActive]}>
              {s.charAt(0).toUpperCase() + s.slice(1)}
            </Text>
          </TouchableOpacity>
        ))}
      </View>

      <ScrollView contentContainerStyle={styles.scroll} keyboardShouldPersistTaps="handled" showsVerticalScrollIndicator={false}>

        {activeSection === 'basics' && (
          <View style={styles.card}>
            <Text style={styles.cardTitle}>Basic info</Text>
            {[
              { label: 'Name', value: name, setter: setName, placeholder: 'Your full name' },
              { label: 'Email', value: email, setter: setEmail, placeholder: 'you@school.edu' },
              { label: 'School & year', value: school, setter: setSchool, placeholder: 'e.g. UCLA, Junior' },
              { label: 'Major', value: major, setter: setMajor, placeholder: 'e.g. Computer Science' },
              { label: 'Preferred location', value: location, setter: setLocation, placeholder: 'e.g. Remote, New York' },
            ].map(f => (
              <View key={f.label} style={styles.fieldGroup}>
                <Text style={styles.fieldLabel}>{f.label}</Text>
                <TextInput
                  style={styles.input}
                  value={f.value}
                  onChangeText={f.setter}
                  placeholder={f.placeholder}
                  placeholderTextColor={Colors.textMuted}
                />
              </View>
            ))}
            <View style={styles.toggleRow}>
              <View style={{ flex: 1 }}>
                <Text style={styles.toggleLabel}>Show scholarship matches</Text>
                <Text style={styles.toggleSub}>Include scholarships in your matches</Text>
              </View>
              <Switch
                value={wantsSchols}
                onValueChange={setWantsSchols}
                trackColor={{ false: Colors.border, true: Colors.primary }}
                thumbColor="#FFFFFF"
              />
            </View>
          </View>
        )}

        {activeSection === 'interests' && (
          <>
            <View style={styles.card}>
              <Text style={styles.cardTitle}>Career fields</Text>
              <View style={styles.chipRow}>
                {CAREER_FIELDS.map(f => (
                  <Chip key={f} label={f} selected={fields.includes(f)} onPress={() => toggle(fields, setFields, f)} />
                ))}
              </View>
            </View>
            <View style={styles.card}>
              <Text style={styles.cardTitle}>Job type preferences</Text>
              <View style={styles.chipRow}>
                {JOB_TYPES.map(t => (
                  <Chip key={t} label={t} selected={types.includes(t)} onPress={() => toggle(types, setTypes, t)} />
                ))}
              </View>
            </View>
          </>
        )}

        {activeSection === 'skills' && (
          <View style={styles.card}>
            <Text style={styles.cardTitle}>Your skills</Text>
            <Text style={styles.cardSub}>Tap suggestions to add · Tap selected to remove</Text>

            {skills.length > 0 && (
              <View style={styles.selectedBox}>
                <Text style={styles.selectedTitle}>Selected ({skills.length})</Text>
                <View style={styles.chipRow}>
                  {skills.map(s => (
                    <TouchableOpacity key={s} style={styles.selectedChip} onPress={() => setSkills(prev => prev.filter(x => x !== s))}>
                      <Text style={styles.selectedChipText}>{s} ×</Text>
                    </TouchableOpacity>
                  ))}
                </View>
              </View>
            )}

            <View style={styles.customRow}>
              <TextInput
                style={styles.customInput}
                placeholder="Type a custom skill..."
                placeholderTextColor={Colors.textMuted}
                value={customSkill}
                onChangeText={setCustomSkill}
                onSubmitEditing={addCustomSkill}
                returnKeyType="done"
              />
              <TouchableOpacity style={styles.addBtn} onPress={addCustomSkill}>
                <Text style={styles.addBtnText}>+ Add</Text>
              </TouchableOpacity>
            </View>

            <View style={styles.chipRow}>
              {SKILL_SUGGESTIONS.filter(s => !skills.includes(s)).map(s => (
                <Chip key={s} label={s} selected={false} onPress={() => setSkills(prev => [...prev, s])} />
              ))}
            </View>
          </View>
        )}

        {activeSection === 'resume' && (
          <View style={styles.card}>
            <Text style={styles.cardTitle}>Resume generator</Text>
            <Text style={styles.cardSub}>
              We'll build a simple resume draft from your skills, major, and career interests. Use it as a starting point in Word or Google Docs.
            </Text>

            <View style={styles.resumePreview}>
              <Text style={styles.resumePreviewTitle}>{name || 'Your Name'}</Text>
              <Text style={styles.resumePreviewLine}>{email}</Text>
              {school && <Text style={styles.resumePreviewLine}>{school}{major ? ' | ' + major : ''}</Text>}
              <View style={styles.resumeDivider} />
              <Text style={styles.resumeSection}>Skills</Text>
              <Text style={styles.resumeSkills}>{skills.length > 0 ? skills.join(' · ') : 'No skills added yet — go to the Skills tab'}</Text>
              <View style={styles.resumeDivider} />
              <Text style={styles.resumeSection}>Career Interests</Text>
              <Text style={styles.resumeSkills}>{fields.length > 0 ? fields.join(', ') : 'Not set'}</Text>
            </View>

            <TouchableOpacity style={styles.generateBtn} onPress={handleGenerateResume} activeOpacity={0.85}>
              <Text style={styles.generateBtnText}>Generate resume draft →</Text>
            </TouchableOpacity>

            <View style={styles.resumeNote}>
              <Text style={styles.resumeNoteText}>
                This generates a text-based starter resume. Paste it into Google Docs or Word and add your experience, education, and projects to complete it.
              </Text>
            </View>
          </View>
        )}

        <TouchableOpacity style={styles.saveBtn} onPress={saveChanges} activeOpacity={0.85}>
          <Text style={styles.saveBtnText}>{saved ? '✓ Saved!' : 'Save changes'}</Text>
        </TouchableOpacity>

      </ScrollView>
    </SafeAreaView>
  )
}

const styles = StyleSheet.create({
  safe:   { flex: 1, backgroundColor: Colors.bg },
  scroll: { padding: Spacing.xl, paddingBottom: Spacing['4xl'] },

  header: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', padding: Spacing.xl, backgroundColor: Colors.surface, borderBottomWidth: 1, borderBottomColor: Colors.border },
  headerLeft: { flexDirection: 'row', alignItems: 'center', gap: Spacing.sm },
  headerTitle: { fontSize: Typography.base, fontWeight: Typography.semibold, color: Colors.textPrimary },
  closeBtn:    { width: 32, height: 32, borderRadius: 16, backgroundColor: Colors.surface2, borderWidth: 1, borderColor: Colors.border, alignItems: 'center', justifyContent: 'center' },
  closeBtnText:{ fontSize: 12, color: Colors.textSecondary, fontWeight: Typography.bold },

  avatarSection: { flexDirection: 'row', alignItems: 'center', gap: Spacing.lg, padding: Spacing.xl, backgroundColor: Colors.surface, borderBottomWidth: 1, borderBottomColor: Colors.border },
  avatar:      { width: 56, height: 56, borderRadius: 28, backgroundColor: Colors.primaryBg, borderWidth: 2, borderColor: Colors.primaryBorder, alignItems: 'center', justifyContent: 'center' },
  avatarText:  { fontSize: Typography.xl, fontWeight: Typography.bold, color: Colors.primary },
  avatarName:  { fontSize: Typography.base, fontWeight: Typography.semibold, color: Colors.textPrimary },
  avatarSchool:{ fontSize: Typography.sm, color: Colors.textMuted, marginTop: 2 },

  sectionTabs: { flexDirection: 'row', backgroundColor: Colors.surface, borderBottomWidth: 1, borderBottomColor: Colors.border, paddingHorizontal: Spacing.xl },
  sectionTab:  { paddingVertical: Spacing.md, paddingHorizontal: Spacing.sm, marginRight: Spacing.md, borderBottomWidth: 2, borderBottomColor: 'transparent' },
  sectionTabActive:  { borderBottomColor: Colors.primary },
  sectionTabText:    { fontSize: Typography.sm, color: Colors.textMuted, fontWeight: Typography.medium },
  sectionTabTextActive: { color: Colors.primary, fontWeight: Typography.semibold },

  card:      { backgroundColor: Colors.surface, borderRadius: Radius.xl, padding: Spacing.xl, borderWidth: 1, borderColor: Colors.border, marginBottom: Spacing.lg, ...Shadows.sm },
  cardTitle: { fontSize: Typography.base, fontWeight: Typography.bold, color: Colors.textPrimary, marginBottom: 4 },
  cardSub:   { fontSize: Typography.xs, color: Colors.textSecondary, marginBottom: Spacing.lg, lineHeight: 18 },

  fieldGroup: { marginBottom: Spacing.md },
  fieldLabel: { fontSize: Typography.sm, fontWeight: Typography.semibold, color: Colors.textPrimary, marginBottom: Spacing.sm },
  input: { backgroundColor: Colors.surface2, borderWidth: 1, borderColor: Colors.border, borderRadius: Radius.md, padding: Spacing.md, fontSize: Typography.base, color: Colors.textPrimary },

  toggleRow:  { flexDirection: 'row', alignItems: 'center', gap: Spacing.md, marginTop: Spacing.md, padding: Spacing.md, backgroundColor: Colors.surface2, borderRadius: Radius.md, borderWidth: 1, borderColor: Colors.border },
  toggleLabel:{ fontSize: Typography.base, color: Colors.textPrimary, fontWeight: Typography.medium },
  toggleSub:  { fontSize: Typography.xs, color: Colors.textMuted, marginTop: 2 },

  chipRow:         { flexDirection: 'row', flexWrap: 'wrap', gap: Spacing.sm },
  chip:            { paddingHorizontal: Spacing.md, paddingVertical: Spacing.sm, borderRadius: Radius.full, backgroundColor: Colors.surface2, borderWidth: 1, borderColor: Colors.border },
  chipSelected:    { backgroundColor: Colors.primaryBg, borderColor: Colors.primary },
  chipText:        { fontSize: Typography.sm, color: Colors.textSecondary },
  chipTextSelected:{ color: Colors.primary, fontWeight: Typography.semibold },

  selectedBox:  { backgroundColor: Colors.successBg, borderRadius: Radius.md, padding: Spacing.md, marginBottom: Spacing.md, borderWidth: 1, borderColor: Colors.successBorder },
  selectedTitle:{ fontSize: Typography.sm, fontWeight: Typography.bold, color: Colors.success, marginBottom: Spacing.sm },
  selectedChip: { backgroundColor: Colors.surface, borderRadius: Radius.full, paddingHorizontal: Spacing.md, paddingVertical: 4, borderWidth: 1, borderColor: Colors.successBorder },
  selectedChipText: { fontSize: Typography.xs, color: Colors.success, fontWeight: Typography.semibold },

  customRow:   { flexDirection: 'row', gap: Spacing.sm, marginBottom: Spacing.md },
  customInput: { flex: 1, backgroundColor: Colors.surface2, borderWidth: 1, borderColor: Colors.border, borderRadius: Radius.md, padding: Spacing.md, fontSize: Typography.base, color: Colors.textPrimary },
  addBtn:      { backgroundColor: Colors.primary, borderRadius: Radius.md, paddingHorizontal: Spacing.lg, justifyContent: 'center' },
  addBtnText:  { color: '#FFFFFF', fontSize: Typography.sm, fontWeight: Typography.bold },

  resumePreview: { backgroundColor: Colors.surface2, borderRadius: Radius.lg, padding: Spacing.xl, marginBottom: Spacing.lg, borderWidth: 1, borderColor: Colors.border },
  resumePreviewTitle: { fontSize: Typography.lg, fontWeight: Typography.bold, color: Colors.textPrimary, marginBottom: 4 },
  resumePreviewLine:  { fontSize: Typography.sm, color: Colors.textSecondary, marginBottom: 2 },
  resumeDivider:  { height: 1, backgroundColor: Colors.border, marginVertical: Spacing.md },
  resumeSection:  { fontSize: Typography.xs, fontWeight: Typography.bold, color: Colors.textSecondary, textTransform: 'uppercase', letterSpacing: 1, marginBottom: Spacing.sm },
  resumeSkills:   { fontSize: Typography.sm, color: Colors.textPrimary, lineHeight: 20 },
  generateBtn:    { backgroundColor: Colors.primary, borderRadius: Radius.md, padding: Spacing.lg, alignItems: 'center', marginBottom: Spacing.md, ...Shadows.md },
  generateBtnText:{ color: '#FFFFFF', fontSize: Typography.base, fontWeight: Typography.bold },
  resumeNote:  { backgroundColor: Colors.infoBg, borderRadius: Radius.md, padding: Spacing.md, borderWidth: 1, borderColor: Colors.infoBorder },
  resumeNoteText: { fontSize: Typography.xs, color: Colors.info, lineHeight: 18 },

  saveBtn:     { backgroundColor: Colors.primary, borderRadius: Radius.lg, padding: Spacing.lg, alignItems: 'center', marginBottom: Spacing.xl, ...Shadows.md },
  saveBtnText: { color: '#FFFFFF', fontSize: Typography.base, fontWeight: Typography.bold },
})
